// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortChatWithAgent() {
  return window['go']['main']['App']['AbortChatWithAgent']();
}

export function AbortSummaryStockNews() {
  return window['go']['main']['App']['AbortSummaryStockNews']();
}

export function AddAllStockInfo(arg1) {
  return window['go']['main']['App']['AddAllStockInfo'](arg1);
}

export function AddCronTask(arg1) {
  return window['go']['main']['App']['AddCronTask'](arg1);
}

export function AddGroup(arg1) {
  return window['go']['main']['App']['AddGroup'](arg1);
}

export function AddPrompt(arg1) {
  return window['go']['main']['App']['AddPrompt'](arg1);
}

export function AddPromptTemplate(arg1) {
  return window['go']['main']['App']['AddPromptTemplate'](arg1);
}

export function AddStockGroup(arg1, arg2) {
  return window['go']['main']['App']['AddStockGroup'](arg1, arg2);
}

export function AddTradingRecord(arg1) {
  return window['go']['main']['App']['AddTradingRecord'](arg1);
}

export function AnalyzeSentiment(arg1) {
  return window['go']['main']['App']['AnalyzeSentiment'](arg1);
}

export function AnalyzeSentimentWithFreqWeight(arg1) {
  return window['go']['main']['App']['AnalyzeSentimentWithFreqWeight'](arg1);
}

export function BatchDeleteAIResponseResult(arg1) {
  return window['go']['main']['App']['BatchDeleteAIResponseResult'](arg1);
}

export function BatchDeleteAllStockInfo(arg1) {
  return window['go']['main']['App']['BatchDeleteAllStockInfo'](arg1);
}

export function CalculateNextRunTime(arg1) {
  return window['go']['main']['App']['CalculateNextRunTime'](arg1);
}

export function CalculateNextRunTimes(arg1, arg2) {
  return window['go']['main']['App']['CalculateNextRunTimes'](arg1, arg2);
}

export function ChatWithAgent(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ChatWithAgent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CheckDeviceBinding(arg1, arg2) {
  return window['go']['main']['App']['CheckDeviceBinding'](arg1, arg2);
}

export function CheckFrequentTrading(arg1) {
  return window['go']['main']['App']['CheckFrequentTrading'](arg1);
}

export function CheckSponsorCode(arg1) {
  return window['go']['main']['App']['CheckSponsorCode'](arg1);
}

export function CheckStockBaseInfo(arg1) {
  return window['go']['main']['App']['CheckStockBaseInfo'](arg1);
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function ClsCalendar() {
  return window['go']['main']['App']['ClsCalendar']();
}

export function CreateCronTask(arg1) {
  return window['go']['main']['App']['CreateCronTask'](arg1);
}

export function CreateMCPServer(arg1) {
  return window['go']['main']['App']['CreateMCPServer'](arg1);
}

export function CreateSkill(arg1) {
  return window['go']['main']['App']['CreateSkill'](arg1);
}

export function DelPrompt(arg1) {
  return window['go']['main']['App']['DelPrompt'](arg1);
}

export function DeleteAIResponseResult(arg1) {
  return window['go']['main']['App']['DeleteAIResponseResult'](arg1);
}

export function DeleteAiRecommendStocks(arg1) {
  return window['go']['main']['App']['DeleteAiRecommendStocks'](arg1);
}

export function DeleteAllStockInfo(arg1) {
  return window['go']['main']['App']['DeleteAllStockInfo'](arg1);
}

export function DeleteCronTask(arg1) {
  return window['go']['main']['App']['DeleteCronTask'](arg1);
}

export function DeleteCustomStrategy(arg1) {
  return window['go']['main']['App']['DeleteCustomStrategy'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function DeletePromptTemplate(arg1) {
  return window['go']['main']['App']['DeletePromptTemplate'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteStockChangeHistory(arg1) {
  return window['go']['main']['App']['DeleteStockChangeHistory'](arg1);
}

export function DeleteTradingRecord(arg1) {
  return window['go']['main']['App']['DeleteTradingRecord'](arg1);
}

export function EMDictCode(arg1) {
  return window['go']['main']['App']['EMDictCode'](arg1);
}

export function EnableCronTask(arg1, arg2) {
  return window['go']['main']['App']['EnableCronTask'](arg1, arg2);
}

export function EnableMCPServer(arg1, arg2) {
  return window['go']['main']['App']['EnableMCPServer'](arg1, arg2);
}

export function EnableSkill(arg1, arg2) {
  return window['go']['main']['App']['EnableSkill'](arg1, arg2);
}

export function ExecuteCronTaskNow(arg1) {
  return window['go']['main']['App']['ExecuteCronTaskNow'](arg1);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function FetchAiModelInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchAiModelInfo'](arg1, arg2, arg3);
}

export function FetchAiModels(arg1, arg2) {
  return window['go']['main']['App']['FetchAiModels'](arg1, arg2);
}

export function FetchAndSaveMarketStatistic() {
  return window['go']['main']['App']['FetchAndSaveMarketStatistic']();
}

export function Follow(arg1) {
  return window['go']['main']['App']['Follow'](arg1);
}

export function FollowFund(arg1) {
  return window['go']['main']['App']['FollowFund'](arg1);
}

export function GetAIResponseResult(arg1) {
  return window['go']['main']['App']['GetAIResponseResult'](arg1);
}

export function GetAIResponseResultList(arg1) {
  return window['go']['main']['App']['GetAIResponseResultList'](arg1);
}

export function GetAiAssistantSession(arg1) {
  return window['go']['main']['App']['GetAiAssistantSession'](arg1);
}

export function GetAiConfigs() {
  return window['go']['main']['App']['GetAiConfigs']();
}

export function GetAiRecommendStocksList(arg1) {
  return window['go']['main']['App']['GetAiRecommendStocksList'](arg1);
}

export function GetAllBKCodes() {
  return window['go']['main']['App']['GetAllBKCodes']();
}

export function GetAllConceptCodes() {
  return window['go']['main']['App']['GetAllConceptCodes']();
}

export function GetAllConcepts() {
  return window['go']['main']['App']['GetAllConcepts']();
}

export function GetAllCustomStrategies() {
  return window['go']['main']['App']['GetAllCustomStrategies']();
}

export function GetAllGroupStocks() {
  return window['go']['main']['App']['GetAllGroupStocks']();
}

export function GetAllIndustries() {
  return window['go']['main']['App']['GetAllIndustries']();
}

export function GetAllMCPTools() {
  return window['go']['main']['App']['GetAllMCPTools']();
}

export function GetAllMarkets() {
  return window['go']['main']['App']['GetAllMarkets']();
}

export function GetAllSkills() {
  return window['go']['main']['App']['GetAllSkills']();
}

export function GetAllStockChangesWithPaging(arg1) {
  return window['go']['main']['App']['GetAllStockChangesWithPaging'](arg1);
}

export function GetAllStockInfoById(arg1) {
  return window['go']['main']['App']['GetAllStockInfoById'](arg1);
}

export function GetAllStockInfoList(arg1) {
  return window['go']['main']['App']['GetAllStockInfoList'](arg1);
}

export function GetAllStocks(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAllStocks'](arg1, arg2, arg3, arg4);
}

export function GetBKFundFlowList(arg1, arg2) {
  return window['go']['main']['App']['GetBKFundFlowList'](arg1, arg2);
}

export function GetBKFundFlowListByDate(arg1, arg2) {
  return window['go']['main']['App']['GetBKFundFlowListByDate'](arg1, arg2);
}

export function GetBKFundFlowTopList(arg1) {
  return window['go']['main']['App']['GetBKFundFlowTopList'](arg1);
}

export function GetBKFundFlowTopListByDate(arg1, arg2) {
  return window['go']['main']['App']['GetBKFundFlowTopListByDate'](arg1, arg2);
}

export function GetChangeRank(arg1, arg2) {
  return window['go']['main']['App']['GetChangeRank'](arg1, arg2);
}

export function GetChangeTypeDailyStats(arg1) {
  return window['go']['main']['App']['GetChangeTypeDailyStats'](arg1);
}

export function GetChipDistribution(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetChipDistribution'](arg1, arg2, arg3, arg4);
}

export function GetConceptFundFlowList(arg1, arg2) {
  return window['go']['main']['App']['GetConceptFundFlowList'](arg1, arg2);
}

export function GetConceptFundFlowListByDate(arg1, arg2) {
  return window['go']['main']['App']['GetConceptFundFlowListByDate'](arg1, arg2);
}

export function GetConceptFundFlowTopList(arg1) {
  return window['go']['main']['App']['GetConceptFundFlowTopList'](arg1);
}

export function GetConceptFundFlowTopListByDate(arg1, arg2) {
  return window['go']['main']['App']['GetConceptFundFlowTopListByDate'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCronTaskByID(arg1) {
  return window['go']['main']['App']['GetCronTaskByID'](arg1);
}

export function GetCronTaskList(arg1) {
  return window['go']['main']['App']['GetCronTaskList'](arg1);
}

export function GetCronTaskTypes() {
  return window['go']['main']['App']['GetCronTaskTypes']();
}

export function GetCustomStrategyList(arg1) {
  return window['go']['main']['App']['GetCustomStrategyList'](arg1);
}

export function GetDailyChangeStats(arg1) {
  return window['go']['main']['App']['GetDailyChangeStats'](arg1);
}

export function GetDailyDimensionStats(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDailyDimensionStats'](arg1, arg2, arg3);
}

export function GetEffectiveSponsorVip() {
  return window['go']['main']['App']['GetEffectiveSponsorVip']();
}

export function GetFollowList(arg1) {
  return window['go']['main']['App']['GetFollowList'](arg1);
}

export function GetFollowedFund() {
  return window['go']['main']['App']['GetFollowedFund']();
}

export function GetFollowedFundPaged(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFollowedFundPaged'](arg1, arg2, arg3);
}

export function GetFundHistoryNetValue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFundHistoryNetValue'](arg1, arg2, arg3, arg4);
}

export function GetFundKLine(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFundKLine'](arg1, arg2, arg3);
}

export function GetFundRanking(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetFundRanking'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetFundTop10Holdings(arg1) {
  return window['go']['main']['App']['GetFundTop10Holdings'](arg1);
}

export function GetGroupList() {
  return window['go']['main']['App']['GetGroupList']();
}

export function GetGroupStockList(arg1) {
  return window['go']['main']['App']['GetGroupStockList'](arg1);
}

export function GetHotStrategy() {
  return window['go']['main']['App']['GetHotStrategy']();
}

export function GetIndustryMoneyRankSina(arg1, arg2) {
  return window['go']['main']['App']['GetIndustryMoneyRankSina'](arg1, arg2);
}

export function GetIndustryRank(arg1, arg2) {
  return window['go']['main']['App']['GetIndustryRank'](arg1, arg2);
}

export function GetLatestTradingDay() {
  return window['go']['main']['App']['GetLatestTradingDay']();
}

export function GetMCPServerByID(arg1) {
  return window['go']['main']['App']['GetMCPServerByID'](arg1);
}

export function GetMCPServerList(arg1) {
  return window['go']['main']['App']['GetMCPServerList'](arg1);
}

export function GetMCPToolsByServerID(arg1) {
  return window['go']['main']['App']['GetMCPToolsByServerID'](arg1);
}

export function GetMachineId() {
  return window['go']['main']['App']['GetMachineId']();
}

export function GetMarketStatisticByDate(arg1) {
  return window['go']['main']['App']['GetMarketStatisticByDate'](arg1);
}

export function GetMoneyRankSina(arg1) {
  return window['go']['main']['App']['GetMoneyRankSina'](arg1);
}

export function GetPromptTemplateList(arg1) {
  return window['go']['main']['App']['GetPromptTemplateList'](arg1);
}

export function GetPromptTemplates(arg1, arg2) {
  return window['go']['main']['App']['GetPromptTemplates'](arg1, arg2);
}

export function GetRecentDaysMarketStatistic(arg1) {
  return window['go']['main']['App']['GetRecentDaysMarketStatistic'](arg1);
}

export function GetSkillByID(arg1) {
  return window['go']['main']['App']['GetSkillByID'](arg1);
}

export function GetSkillList(arg1) {
  return window['go']['main']['App']['GetSkillList'](arg1);
}

export function GetSponsorInfo() {
  return window['go']['main']['App']['GetSponsorInfo']();
}

export function GetStockChangeHistory(arg1) {
  return window['go']['main']['App']['GetStockChangeHistory'](arg1);
}

export function GetStockChanges(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStockChanges'](arg1, arg2, arg3);
}

export function GetStockCommonKLine(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStockCommonKLine'](arg1, arg2, arg3);
}

export function GetStockEastMoneyKLine(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetStockEastMoneyKLine'](arg1, arg2, arg3, arg4);
}

export function GetStockEastMoneyKLinePage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetStockEastMoneyKLinePage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStockKLine(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStockKLine'](arg1, arg2, arg3);
}

export function GetStockKLinePageWithFallback(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetStockKLinePageWithFallback'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetStockKLineWithFallback(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetStockKLineWithFallback'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStockList(arg1) {
  return window['go']['main']['App']['GetStockList'](arg1);
}

export function GetStockMinutePriceLineData(arg1, arg2) {
  return window['go']['main']['App']['GetStockMinutePriceLineData'](arg1, arg2);
}

export function GetStockMoneyTrendByDay(arg1, arg2) {
  return window['go']['main']['App']['GetStockMoneyTrendByDay'](arg1, arg2);
}

export function GetStockRealTimePrice(arg1) {
  return window['go']['main']['App']['GetStockRealTimePrice'](arg1);
}

export function GetTdxCallAuction(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTdxCallAuction'](arg1, arg2, arg3);
}

export function GetTdxCompanyCategoryContent(arg1, arg2) {
  return window['go']['main']['App']['GetTdxCompanyCategoryContent'](arg1, arg2);
}

export function GetTdxCompanyCategoryList(arg1) {
  return window['go']['main']['App']['GetTdxCompanyCategoryList'](arg1);
}

export function GetTdxCompanyInfo(arg1) {
  return window['go']['main']['App']['GetTdxCompanyInfo'](arg1);
}

export function GetTdxFinanceInfo(arg1) {
  return window['go']['main']['App']['GetTdxFinanceInfo'](arg1);
}

export function GetTdxSymbolBelongBoard(arg1) {
  return window['go']['main']['App']['GetTdxSymbolBelongBoard'](arg1);
}

export function GetTdxXDXRInfo(arg1) {
  return window['go']['main']['App']['GetTdxXDXRInfo'](arg1);
}

export function GetTelegraphList(arg1) {
  return window['go']['main']['App']['GetTelegraphList'](arg1);
}

export function GetTimezone() {
  return window['go']['main']['App']['GetTimezone']();
}

export function GetTodayMarketStatistic() {
  return window['go']['main']['App']['GetTodayMarketStatistic']();
}

export function GetTradingRecordById(arg1) {
  return window['go']['main']['App']['GetTradingRecordById'](arg1);
}

export function GetTradingRecordList(arg1) {
  return window['go']['main']['App']['GetTradingRecordList'](arg1);
}

export function GetTradingRecordStatistics() {
  return window['go']['main']['App']['GetTradingRecordStatistics']();
}

export function GetTypeStatsByDate(arg1) {
  return window['go']['main']['App']['GetTypeStatsByDate'](arg1);
}

export function GetUplimitHot(arg1, arg2) {
  return window['go']['main']['App']['GetUplimitHot'](arg1, arg2);
}

export function GetUserManual() {
  return window['go']['main']['App']['GetUserManual']();
}

export function GetVersionInfo() {
  return window['go']['main']['App']['GetVersionInfo']();
}

export function GetfundList(arg1) {
  return window['go']['main']['App']['GetfundList'](arg1);
}

export function GlobalStockIndexes() {
  return window['go']['main']['App']['GlobalStockIndexes']();
}

export function GlobalStockIndexesReadable() {
  return window['go']['main']['App']['GlobalStockIndexesReadable']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function HotEvent(arg1) {
  return window['go']['main']['App']['HotEvent'](arg1);
}

export function HotStock(arg1) {
  return window['go']['main']['App']['HotStock'](arg1);
}

export function HotTopic(arg1) {
  return window['go']['main']['App']['HotTopic'](arg1);
}

export function IndustryResearchReport(arg1) {
  return window['go']['main']['App']['IndustryResearchReport'](arg1);
}

export function InitCronTasks() {
  return window['go']['main']['App']['InitCronTasks']();
}

export function InitializeGroupSort() {
  return window['go']['main']['App']['InitializeGroupSort']();
}

export function InvestCalendarTimeLine(arg1) {
  return window['go']['main']['App']['InvestCalendarTimeLine'](arg1);
}

export function IsHKTradingTime() {
  return window['go']['main']['App']['IsHKTradingTime']();
}

export function IsTradingDay(arg1) {
  return window['go']['main']['App']['IsTradingDay'](arg1);
}

export function IsTradingTime() {
  return window['go']['main']['App']['IsTradingTime']();
}

export function IsUSTradingTime() {
  return window['go']['main']['App']['IsUSTradingTime']();
}

export function LongTigerRank(arg1) {
  return window['go']['main']['App']['LongTigerRank'](arg1);
}

export function NewChatStream(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['NewChatStream'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function NewsPush(arg1) {
  return window['go']['main']['App']['NewsPush'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PromptPlazaRequest(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PromptPlazaRequest'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReFleshTelegraphList(arg1) {
  return window['go']['main']['App']['ReFleshTelegraphList'](arg1);
}

export function RemoveGroup(arg1) {
  return window['go']['main']['App']['RemoveGroup'](arg1);
}

export function RemoveStockGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveStockGroup'](arg1, arg2, arg3);
}

export function RestartAsAdmin() {
  return window['go']['main']['App']['RestartAsAdmin']();
}

export function SaveAIResponseResult(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveAIResponseResult'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveAiAssistantSession(arg1, arg2) {
  return window['go']['main']['App']['SaveAiAssistantSession'](arg1, arg2);
}

export function SaveAsMarkdown(arg1, arg2) {
  return window['go']['main']['App']['SaveAsMarkdown'](arg1, arg2);
}

export function SaveCustomStrategy(arg1) {
  return window['go']['main']['App']['SaveCustomStrategy'](arg1);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SaveStockChangesToHistory(arg1) {
  return window['go']['main']['App']['SaveStockChangesToHistory'](arg1);
}

export function SaveWordFile(arg1, arg2) {
  return window['go']['main']['App']['SaveWordFile'](arg1, arg2);
}

export function SearchCronTasks(arg1) {
  return window['go']['main']['App']['SearchCronTasks'](arg1);
}

export function SearchFundCodes(arg1) {
  return window['go']['main']['App']['SearchFundCodes'](arg1);
}

export function SearchStock(arg1) {
  return window['go']['main']['App']['SearchStock'](arg1);
}

export function SendDingDingMessage(arg1, arg2) {
  return window['go']['main']['App']['SendDingDingMessage'](arg1, arg2);
}

export function SendDingDingMessageByType(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendDingDingMessageByType'](arg1, arg2, arg3);
}

export function SendFeishuMessage(arg1, arg2) {
  return window['go']['main']['App']['SendFeishuMessage'](arg1, arg2);
}

export function SendFeishuMessageByType(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendFeishuMessageByType'](arg1, arg2, arg3);
}

export function SetAlarmChangePercent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAlarmChangePercent'](arg1, arg2, arg3);
}

export function SetCostPriceAndVolume(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCostPriceAndVolume'](arg1, arg2, arg3);
}

export function SetStockAICron(arg1, arg2) {
  return window['go']['main']['App']['SetStockAICron'](arg1, arg2);
}

export function SetStockSort(arg1, arg2) {
  return window['go']['main']['App']['SetStockSort'](arg1, arg2);
}

export function SetTradingPrice(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetTradingPrice'](arg1, arg2, arg3, arg4, arg5);
}

export function ShareAnalysis(arg1, arg2) {
  return window['go']['main']['App']['ShareAnalysis'](arg1, arg2);
}

export function ShareText(arg1, arg2) {
  return window['go']['main']['App']['ShareText'](arg1, arg2);
}

export function ShowFromTray() {
  return window['go']['main']['App']['ShowFromTray']();
}

export function StockNotice(arg1) {
  return window['go']['main']['App']['StockNotice'](arg1);
}

export function StockResearchReport(arg1) {
  return window['go']['main']['App']['StockResearchReport'](arg1);
}

export function SummaryStockNews(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SummaryStockNews'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function TestMCPServer(arg1) {
  return window['go']['main']['App']['TestMCPServer'](arg1);
}

export function UnFollow(arg1) {
  return window['go']['main']['App']['UnFollow'](arg1);
}

export function UnFollowFund(arg1) {
  return window['go']['main']['App']['UnFollowFund'](arg1);
}

export function UpdateAiRecommendStocksAlert(arg1, arg2) {
  return window['go']['main']['App']['UpdateAiRecommendStocksAlert'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateCronTask(arg1) {
  return window['go']['main']['App']['UpdateCronTask'](arg1);
}

export function UpdateGroup(arg1, arg2) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2);
}

export function UpdateGroupSort(arg1, arg2) {
  return window['go']['main']['App']['UpdateGroupSort'](arg1, arg2);
}

export function UpdateMCPServer(arg1) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1);
}

export function UpdatePromptTemplate(arg1) {
  return window['go']['main']['App']['UpdatePromptTemplate'](arg1);
}

export function UpdateSkill(arg1) {
  return window['go']['main']['App']['UpdateSkill'](arg1);
}

export function UpdateTradingRecord(arg1) {
  return window['go']['main']['App']['UpdateTradingRecord'](arg1);
}

export function ValidateCronExpr(arg1) {
  return window['go']['main']['App']['ValidateCronExpr'](arg1);
}
